ortho

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+command -v mysql >/dev/null 2>&1 || { echo >&2 "Mysql has to be installed to use the application.  Aborting."; exit 1; }
+command -v qmake >/dev/null 2>&1 || { echo >&2 "Did not find the qmake command.  Aborting."; exit 1; }
+
 sslVersion=$(openssl version)
 
 if [[ $sslVersion != "OpenSSL 1.0.1g"* ]]
